line = input("Enter any string\n")
print(line.isalpha())
print(line.isalnum())
print(line.isascii())
print(line.isdigit())
print(line.islower())
print(line.find("shu"))
print(line.replace("shu","him"))
print(line.strip('sma'))
